name:                milter
version:             0.1.0.0
github:              "An-Death/HaskellMilter"
license:             BSD3
author:              "Aleksey Simuskov"
maintainer:          "opiumofthepeople@yancdex.ru"
copyright:           "Copyright (c) Aleksey Simuskov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/An-Death/HaskellMilter#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules:
    - Network.Milter
    - Network.Milter.Protocol
  dependencies:
    - bytestring
    - iproute
    - binary


executables:
  HaskellMilter-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - milter
    - network-simple
    - network
    - bytestring

tests:
  HaskellMilter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - milter
